server {
  listen 80; # Nginx will listen on port 80 inside the container

  root /usr/share/nginx/html; # This is where your Angular files will be copied

  index index.html;

  location / {
    try_files $uri $uri/ /index.html; # Essential for Angular client-side routing (deep links)
  }

  # Optional: Add caching headers for static assets
  location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|eot|otf|ttf|woff|woff2)$ {
    expires 30d;
    add_header Cache-Control "public, no-transform";
  }
}
